name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Build the Docker image
        run: |
          tNow=$(date +%s)
          docker build . --file Dockerfile --tag "${{ secrets.DOCKER_USERNAME }}"/dotnet-nuget:latest --tag "${{ secrets.DOCKER_USERNAME }}"/dotnet-nuget:"$tNow"
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push "${{ secrets.DOCKER_USERNAME }}"/dotnet-nuget:"$tNow"
          docker push "${{ secrets.DOCKER_USERNAME }}"/dotnet-nuget:latest
