name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
    - run: tNow=$(date +%s)
    - run: docker build . --file Dockerfile --tag dotnet-nuget:"$tNow"
    - run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
    - run: docker push "${{ secrets.DOCKER_USERNAME }}"/dotnet-nuget:"$tNow"
